<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\ExamLink;
use App\Models\School;
use Illuminate\Http\Request;

class HandshakeController extends Controller
{
    /**
     * Verify QR Token and return Exam URL
     * Expected inputs from Android App: school_id, token, signature
     */
    public function verify(Request $request)
    {
        $schoolId = $request->input('school_id');
        $token = $request->input('token');
        $signature = $request->input('signature'); // the 8-char chunk from QR
        
        if (!$token || !$schoolId || !$signature) {
            return response()->json([
                'success' => false,
                'message' => 'Format QR tidak valid atau kurang lengkap'
            ], 400);
        }

        // 1. SECURITY HANDSHAKE (Signature Verification)
        // This ensures the QR was actually generated by this admin panel
        $secretKey = config('app.key');
        $expectedSignature = hash_hmac('sha256', $schoolId . '|' . $token, $secretKey);
        $expectedSigPart = substr($expectedSignature, 0, 8);

        if ($signature !== $expectedSigPart) {
            return response()->json([
                'success' => false,
                'message' => 'QR Code tidak sah atau telah dimanipulasi'
            ], 403);
        }

        // 2. DATABASE VERIFICATION
        $examLink = ExamLink::with('school')
            ->where('secure_token', $token)
            ->where('school_id', $schoolId)
            ->where('is_active', true)
            ->first();

        if (!$examLink) {
            return response()->json([
                'success' => false,
                'message' => 'Data ujian tidak ditemukan atau link sudah kadaluarsa'
            ], 404);
        }

        // 3. INSTITUTION STATUS (Manual Suspend)
        if (!$examLink->school->is_active) {
            return response()->json([
                'success' => false,
                'message' => 'Akses Instansi sedang ditangguhkan oleh Pusat'
            ], 403);
        }

        // 4. SUBSCRIPTION STATUS
        if (!$examLink->school->isSubscriptionActive()) {
            return response()->json([
                'success' => false,
                'message' => 'Masa langganan Instansi ini telah berakhir. Silakan hubungi admin.'
            ], 402);
        }

        // 5. SUCCESS RESPOND
        // Return full details including whitelist for the Android Secure Browser
        return response()->json([
            'success' => true,
            'data' => [
                'school_id' => $examLink->school_id,
                'school_name' => $examLink->school->name,
                'exam_title' => $examLink->title,
                'exam_url' => $examLink->exam_url,
                'domain_whitelist' => $examLink->school->domain_whitelist,
                'authorized_at' => now()->toIso8601String(),
            ]
        ]);
    }
}
